.gitignore
package.json
src/message/index.js

Ref https://github.com/ipfs/js-ipfs/issues/991

feat: replace protocol-buffers with protons

---

src/index.js
src/message/dht.proto.js

Initially our DHT was meant to get some of Coral's features (cluster rings -- that's why there's `clusterRawLevel`), but we never got to it. Let's strip the mentions of it.

docs: remove mentions of coral, it's not implemented

---

package.json
src/index.js
src/peer-queue.js
src/private.js
src/query.js
src/rpc/handlers/get-value.js
src/rpc/handlers/put-value.js
src/utils.js
test/providers.spec.js

The logs are currently returning utf-8 strings for many of the key references in the dht. This makes the data very unhelpful for users. This PR adds a base58 formatter for `debug` via `multihashes` and updates the logs across the file where needed.
I also noticed the expire test for providers was flaky because of the timeouts. The interval was set to 100 and the expire was set to 200. The test check was only at 300, which it is possible for the cleanup to trigger after. I've upped the test to 400ms, although being able to monitor the cleanup would be ideal, to prevent the flakiness. I've re-run the tests a couple time to verify, https://ci.ipfs.team/blue/organizations/jenkins/libp2p%2Fjs-libp2p-kad-dht/activity?branch=fix%2Flogs.

Make logs better for users and fix flaky test

---

src/index.js

findPeer currently sets a default timeout if one is not given, this updates findProviders to do the same. If a timeout is not given, the call will immediately timeout and return an ETIMEDOUT error.
The default timeout is set to 1 minute, to match findPeer.

fix: make findProviders treat timeout the same as findPeer

---

package.json
src/index.js
test/kad-dht.spec.js

Aiming to allow other future options to `findPeer` and `findProviders`, I changed the`maxTimeout` param to an object `options`.
In the context of 
- [js-libp2p-delegated-content-routing#6](https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/6)
- [js-libp2p-delegated-peer-routing#6](https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/6)

fix: find peer and providers options

---

package.json
src/index.js
src/random-walk.js
test/kad-dht.spec.js
test/utils/test-dht.js

In the context of the integration of the DHT to `js-ipfs` [js-ipfs#856](https://github.com/ipfs/js-ipfs/pull/856).
I changed the implementation of `randomWalk`. It was using a `setInterval`, which was causing this function to run the `_walk` function after five minutes. On the contrary, `go-libp2p-kad-dht` runs immediately after the node starts and then, each 5 minutes, as we can see in [go-libp2p-kad-dht/dht_bootstrap.go#L81-L85](https://github.com/libp2p/go-libp2p-kad-dht/blob/master/dht_bootstrap.go#L81-L85)
Worklist:

feat: start random walk and allow configuration for disabling

---

package.json
src/index.js
src/private.js
src/rpc/handlers/get-value.js
src/utils.js
test/kad-dht.spec.js
test/message.spec.js
test/rpc/handlers/get-value.spec.js
test/rpc/handlers/put-value.spec.js

The `libp2p-record` module was updated to interop with `go-libp2p-record`.  As a result, the author and signature were removed, as well as all the logic inherent to the signature.
More info [js-libp2p-record#8](https://github.com/libp2p/js-libp2p-record/pull/8)

chore: upgrade libp2p record version

---

src/private.js
test/kad-dht.spec.js

`dht._putValueToPeer` was receiving the parameters in a wrong order, for this case.

fix: record outdated local correction

---

package.json
src/private.js
test/kad-dht.spec.js
test/utils/test-dht.js

Select first record when no selector function exists for it. Currently, it throws an handled exception and `go-ipfs` allows other types of keys.

feat: select first record when no selector function

---

src/index.js
test/kad-dht.spec.js

Allow configurable validators and selectors. Users of `libp2p-kad-dht` must be able to set their own validators and selectors. 
For instance, this is important for `js-ipfs` to use `/ipns/` namespaces in the DHT

feat: allow configurable validators and selectors

---

test/kad-dht.spec.js

The test was assuming that all peers are reachable, which isn't necessarily true.

fix: make 'find peer query' test reliable

---

src/constants.js
src/index.js
src/private.js
src/query.js
src/utils.js
test/query.spec.js
test/utils/create-disjoint-tracks.js

This implements one of the core extensions of S/Kademlia.
Fixes #37. Existing tests are passing but new tests are still needed.
Could I get some feedback on this before doing the go version?

Do parallel lookups on disjoint sets of nodes

---

src/index.js
src/private.js
src/random-walk.js
test/kad-dht.spec.js

`maxTimeout ` option property renamed to `timeout`. Moreover, previous support for timeout using a number instead of an object with options deprecated.
BREAKING CHANGE: get, getMany, findProviders and findPeer do not accept a timeout number anymore. It must be a property of an object options.

chore: update options timeout property

---

package.json
src/index.js
src/network.js
src/query.js
test/kad-dht.spec.js

Add emit event on peer connected.
Required by #61

feat: emit event on peer connected

---

src/index.js
test/kad-dht.spec.js

put call fails if any node fails for any reason - including disconnected, node doesn’t support kad protocol, etc.  Changed behavior to be able to provide a minimum number of peers to write to to be considered a “successful put”.  Default put peers required was chosen as 0 so as to be a non-breaking change
Fix for #68

fix: specify # of peers for successful put

---

src/network.js
test/kad-dht.spec.js
test/query.spec.js

This PR prevents the DHT claiming discovery of a peer that it may not have even discovered and also multiple discoveries of the same peer.
DHT was listening for 'peer-mux-established' from the switch and emitting a 'peer' event in response to it. Listening to 'peer-mux-established' implies that the peer has _already_ been discovered so there's no need to emit it again and moreover the peer may not have been discovered by the DHT in the first place!

fix: false discovery

---

src/index.js
src/private.js
src/query.js
test/query.spec.js
test/utils/create-disjoint-tracks.js

Currently queries continue running
- after there was a timeout
- after a match is found on one disjoint path (eg in find peer)
This PR changes the query function to return either `pathComplete` or `queryComplete`, where `queryComplete` indicates that the whole query should stop (not just this particular disjoint path)
It also ensures that queries are stopped after a timeout or any other error.

Ensure queries stop after error or success

---

src/index.js
src/query-manager.js
src/query.js
test/kad-dht.spec.js
test/query.spec.js

Make sure that any running queries are stopped when the DHT stops

Stop running queries on shutdown

---

src/constants.js
src/index.js
src/random-walk.js
test/kad-dht.spec.js

resolves https://github.com/libp2p/js-libp2p-kad-dht/issues/100
This adds support for `delay` in the random walk config. This allows random walk to be run more quickly after startup, while maintaining a longer interval.
I ran this against js-ipfs master with a randomWalk config (all options aside from enabled are default):
```js
randomWalk: {
enabled: true,
interval: 300e3,
delay: 10e3,
timeout: 10e3
}
```
With an idle node, I had 100+ connected peers in under a minute. The connected peers eventually stabilized around the max peers of ~300.
**logging**: I also updated the randomConfig logging to make it easier to target for debugging. Instead of `DEBUG=libp2p:dht` and sifting through the logs, you can now have `DEBUG=libp2p:dht:random-walk*` and follow only random walk logs, and error …

feat: add delay support to random walk

---

.aegir.js
src/constants.js
src/index.js
src/peer-distance-list.js
src/query.js
test/kad-dht.spec.js
test/peer-distance-list.spec.js
test/query.spec.js

Implements https://github.com/libp2p/go-libp2p-kad-dht/issues/290
Stop querying once we have successfully queried >= K peers, and the only remaining peers waiting to be queried are further from the key than those K peers.
I also fixed a bug where we would return peers that we hadn't successfully connected to and refactored the Query class.

Limit scope of queries to k closest peers

---

package.json
src/constants.js
src/index.js
src/random-walk.js
test/kad-dht.spec.js
test/random-walk.spec.js
test/utils/test-dht.js

Random Walk had some bugs, this fixes them: 
* If you ever specified more than 1 query, it would never run them. (You really shouldn;t need more than 1, but still not a good bug)
* We timed out the walk, but `findPeer` wasn't given the walks timeout. So if you specified 10seconds as your walk timeout, the `findPeer` logic would keep running until its default timeout kicked in (60 seconds)
I added a suite of tests just for RandomWalk to test the failures I was seeing.
This also adds support for AbortController in random walk and passes it to findPeer, **however**, findPeer currently isn't listening to the abort signal so it won't actually stop the query. My thought is to wait until we finish #82 and then add the abort logic to all of the query methods. Once we do, random walk will …

fix: random walk

---

package.json

BREAKING CHANGE: v1 CIDs are now encoded in base32 when stringified.
https://github.com/ipfs/js-ipfs/issues/1995

chore: update cids dependency

---

src/private.js

I noticed negative values for `pathSize`

Bug Fix: correctly calculate pathSize in _findNProviders

---

.aegir.js
test/kad-dht.spec.js

Added tests using 8 different nodes, in order to create some stress in the DHT.
During this tests, I found a bug regarding the local correction of outdated records. This way, the tests for this PR fail sometimes while the following PR is not merged:

tests: multiple nodes

---

src/index.js
src/peer-queue.js
src/private.js
src/query/index.js
src/query/path.js
src/query/run.js
src/query/workerQueue.js
test/peer-queue.spec.js
test/query.spec.js
test/query/index.spec.js

non-breaking async refactor for
- `Query`
- `Run`
- `Path` 
- `PeerQueue`
this is intended to *not* introduce any changes in behavior
related #82

refactor(async): Query

---

.travis.yml
package.json

This does 2 things:
1. Removes commitlint on Travis: We shouldnt block travis builds with commitlint. Instead, we should ensure commit messages are formatted correctly by updating the messages via squashing merging the PRs. This keeps the barrier to entry low, while allowing maintainers to keep changelog messaging clean.
2. Removes test running on pre-push. Linting is fine, but the test suite is rather long, let's have CI take care of that.

chore: remove commitlint and pre-push test runs

---

.aegir.js
src/index.js
test/kad-dht.spec.js
test/rpc/handlers/add-provider.spec.js

In the payload for ADD_PROVIDER we were sending remote peers their own id instead of the local node's id. The tests still passed because on the receiving end we ignore the payload and just look at the connection to get the provider peer id.

Fix: send correct payload in ADD_PROVIDER RPC

---

src/rpc/handlers/add-provider.js
test/rpc/handlers/add-provider.spec.js

Fixes https://github.com/libp2p/js-libp2p-kad-dht/issues/128

Fix: favour providers peerInfo over sender peerInfo in ADD_PROVIDER

---

src/index.js
src/private.js
src/query/path.js
src/query/workerQueue.js
src/utils.js
test/kad-dht.spec.js
test/kad-utils.spec.js
test/query.spec.js
test/query/index.spec.js
test/random-walk.spec.js

This refactor changes the `queryFn`s to be async. The `makePath` functions are still synchronous
```js
const q = new Query(dht, peer.id.id, () => {
// makePath: do once-per-path setup
return async () => {
// queryFn: do actual query
}
})
```
No behavioral changes were intended, but some tests needed timeouts added to their query functions in order to resolve as expected
related #82

Async Refactor: query functions are now async functions

---

.aegir.js
package.json
src/index.js
src/private.js
src/providers.js
src/rpc/handlers/add-provider.js
src/rpc/handlers/get-providers.js
test/providers.spec.js
test/rpc/handlers/add-provider.spec.js
test/rpc/handlers/get-providers.spec.js

providers.js hasn't been touched in a while, so this is mostly directly taken from #82
Added some async/callback wrappers here and there and used `pull-stream-to-async-iterator` around  `datastore.query` as #82 originally relied on the new datastore interface
Fixes #124

Async Refactor: providers

---

.aegir.js
package.json
src/random-walk.js
test/random-walk.spec.js

switched over to a `_running` state var and and `while(true)` async loop instead of managing `timeoutId`s
skipped a test that was expecting queries to be run in series and that errors would stop the other queries. Should an error in `_walk` trigger `randomWalk` to stop? currently we log and ignore
updates #82

Async Refactor: random-walk

---

src/private.js

When `_findNProvidersAsync` times out, it ignores the search results, as it's checking the `out` array before it's actually populated.

fix _findNProvidersAsync discarding search results

---

package.json
src/private.js
src/providers.js
src/query/index.js
src/rpc/handlers/get-providers.js
src/rpc/handlers/put-value.js
src/utils.js
test/kad-dht.spec.js
test/kad-utils.spec.js
test/providers.spec.js
test/query.spec.js
test/query/index.spec.js
test/random-walk.spec.js
test/rpc/handlers/get-providers.spec.js
test/rpc/handlers/put-value.spec.js
test/simulation/index.js

BREAKING CHANGE: This change requires datastores that comply with interface-datastore@0.7.0 or later.
This refactors internal usage of `datastore` to use the async api. I also bumped `aegir` and fixed linting. Many of the rules for `require-async` are ignored at the moment, they should be removed once the full conversion is done.
**Note:** the libp2p-record update is the last dependency needed to convert to full async/await.

refactor: use async datastore

---

package.json
src/providers.js

`js-libp2p-kad-dht`'s dependence on `p-queue@^5.0.0` is causing issues when running IPFS from inside of Electron.
https://github.com/ipfs/js-ipfs/issues/2374
- This bumps p-queue to `^6.0.0`
Does this repo require me to manually bump the semver in the package.json? Or do you handle that?

Bumped p-queue to ^6.0.0

---

src/network.js
test/kad-dht.spec.js

For consistency with other `libp2p` subsystems, `dht.start` when the dht is already started and `dht.stop` when the dht is not started should not throw an error

fix: stop and start not fail

---

src/constants.js
src/network.js
src/rpc/index.js
src/utils.js

Fixes https://github.com/libp2p/js-libp2p-kad-dht/issues/154

Remove extraneous message size filter

---

src/content-fetching/index.js
src/content-routing/index.js
src/index.js
src/peer-routing/index.js
test/kad-dht.spec.js

This PR aims to get consistency with `libp2p-delegated-*-routing`, as well as with `libp2p-daemon`
BREAKING CHANGE: API for find providers  and closest peers return async iterable instead of an array of PeerInfo
Closes #151

feat: find providers and closest peers return async iterable

---

src/content-routing/index.js
test/kad-dht.spec.js

If the locally known providers were enough to achieve the `maxNumProviders` option, they were not being yield, but returned

fix: find providers should yield when found locally

---

src/content-fetching/index.js
test/kad-dht.spec.js

Currently, putting and getting data from the same node fails because teh node has no peers on the routing table.
Per the previous behaviour:
https://github.com/libp2p/js-libp2p-kad-dht/blob/v0.16.1/src/index.js#L335-L394

fix: get many should not fail if found locally

---

src/query/path.js
src/query/workerQueue.js

During queries, whenever a Peer is queried directly it is added to the `peersSeen` Set, which prevents us from querying them again. The issue is that currently `peerSeen` is a Set of `PeerId`. Whenever we learn about peers from the network, the deserialized PeerIds are created as new objects, which will cause them to be added to the set even if they belong to the same peer. This fixes that by using the string of the peer id and making `peerSeen` a string Set for better equality checking.

fix: dont use peer ids in sets

---

src/index.js
src/message/index.js
src/random-walk.js
test/random-walk.spec.js

The polyfill is big, we can simulate it by throwing an Error and it doesn't work under React Native.

fix: remove use of assert module

---

package.json
src/content-routing/index.js
src/index.js
src/peer-routing/index.js
src/query/workerQueue.js
src/rpc/handlers/add-provider.js
src/rpc/handlers/get-providers.js
src/rpc/handlers/get-value.js
test/kad-dht.spec.js
test/query/index.spec.js
test/rpc/handlers/add-provider.spec.js
test/rpc/handlers/get-value.spec.js
test/rpc/index.spec.js
test/simulation/index.js
test/utils/test-dht.js

In the context of the PeerStore improvements specified on [libp2p/js-libp2p#582](https://github.com/libp2p/js-libp2p/issues/582) and as a follow up of [libp2p/js-libp2p#590](https://github.com/libp2p/js-libp2p/pull/590), this PR switches `libp2p-kad-dht` usage of `peer-store` to its new API.
Moreover, there were some places where data was being added to the `peerStore` with any benefit. In some cases the data was already there and in other cases there was nothing new to add at that point.
BREAKING CHANGE: uses new peer-store api
Needs:
Unblocks:

chore: use new peer store api

---

src/index.js
src/query/workerQueue.js

In the context of deprecating `peer-info` as described on [libp2p/js-libp2p#589](https://github.com/libp2p/js-libp2p/issues/589), this PR changes the `peer-discovery` interface to emit an object containing an `id` property and a `multiaddrs` property.
We still do not run the interface tests per #44 . 
BREAKING CHANGE: peer event emits an object with id and multiaddr instead of a peer-info
Needs:

chore: peer-discovery not using peer-info

---

package.json
src/content-routing/index.js
src/index.js
src/peer-routing/index.js
test/rpc/handlers/add-provider.spec.js

Per [libp2p/js-libp2p#610](https://github.com/libp2p/js-libp2p/pull/610) review, we are renaming `MultiaddrInfo` into `Address`, and `peerStore.get` return value from `PeerData` into `peer` with an `addresses` property instead of `multiaddrInfos`.
This needs:

chore: rename peer-store properties

---

src/peer-routing/index.js
test/rpc/handlers/get-value.spec.js

Add peer public key to the `keyBook`. This was previously achieve by an internal `peerIds` datastructure.
Needs:

chore: use keybook

---

package.json
src/index.js
src/providers.js
test/providers.spec.js

After debugging one `js-ipfs` example hanging, I found this leaking issue.
When `js-libp2p` is created, the `dht` will be created if enabled. When the `dht` is enabled, it will be instantiated. During the instantiation, `Providers` was also instantiated and a setter was starting a timer. If the dht was created, but not started, when a process is closing, this timer was not cleared, since the stop was also not called.

fix: providers leaking resources on dht construction

---

src/content-fetching/index.js
src/content-routing/index.js
src/utils.js

Fixes https://github.com/libp2p/js-libp2p-kad-dht/issues/164
There's still one more place where we handle things serially: handling incoming messages for a single peer. I decided not to touch it. It could be addressed with [`paramap-it`](https://github.com/alanshaw/paramap-it), likely with `ordered: false` option

fix: use utils.mapParallel for parallel processing of peers

---

package.json
src/query/index.js
src/utils.js
test/simulation/index.js

Also removes the multihashes dependency in favour of the one exported from `multihashing-async`.

chore: update deps

---

src/network.js
test/utils/index.js

Ideally libp2p should just get passed to the DHT and dial should be used, instead of interacting with the dialer. Currently the dialer does not check for existing connections, like libp2p.dial() does.
This issue was found at https://discuss.libp2p.io/t/random-walk-peer-discovery-adds-connections-to-same-peer/584/2. I tested the change against the sample code shared and it kept the connection count at 1 per peer.
We should probably look at updated the constructor in libp2p 0.29 to just take libp2p, instead of passing numerous components, and make that breaking change here to accompany it. We could also wait for the DHT updates before doing this.

fix: check for an existing connection before using the dialer

---

src/index.js
src/network.js
test/kad-dht.spec.js
test/utils/test-dht.js

This adds the ability for DHT nodes to run in client mode. This means, nodes will not register nor respond to queries on the dht protocol, which nodes **should** be doing if they are not dialable (browser nodes, nodes behind NATs)
Ideally, this should be dynamic and should be in client mode by default, however, js-libp2p doesn't currently have autoNat support so we can't dynamically determine our dialability.
To keep this backwards compatible clientMode is disabled by default.
I left `_clientMode` as private for now. In the future we may want to add a setter to allow this to be changed dynamically.

feat: add support for client mode

---

package.json
src/content-routing/index.js
src/index.js
src/network.js
test/kad-dht.spec.js
test/utils/test-dht.js

I was adding some additional tests post https://github.com/libp2p/js-libp2p-kad-dht/pull/200 which exposed a couple issues with provide calls.
1. The `ADD_PROVIDER` rpc was never being sent, as no sync was set up in the pipe. This corrects that with `consume`.
1. We weren't adding our addresses to the provider record. We lost this during the peerinfo migration. `libp2p@0.28.5` includes a [patch](https://github.com/libp2p/js-libp2p/pull/700) to pass libp2p to the dht constructor to give it access. _We can simplify the constructor in a future breaking change._
The reason the tests didn't catch this is that the dht connects to and queries the provider, but they can't do this with a dht client, they need to get the provider record from another DHT server. Since the provider record wasn't …

fix: actually send the add provider rpc with addresses

---

src/index.js
src/rpc/handlers/put-value.js
test/kad-dht.spec.js
test/rpc/handlers/put-value.spec.js

This PR adds two events that provide notification of state changes to the local datastore of the DHT for content (ie non peer routing entries). Includes tests.
See https://github.com/libp2p/js-libp2p-kad-dht/pull/204 for previous discussion.
This solves libp2p/js-libp2p#794
Usage:
```javascript
dht.onPut = (record, peerId) => {}
dht.onRemove = (record) => {}
```

Feature: onPut and onRemove events

---

README.md
src/constants.js
src/index.js
src/network.js
test/kad-dht.spec.js
test/utils/test-dht.js

This PR adds the ability to use unique multicodec protocols for the DHT, which enables multiple DHTs to operate separately in a single libp2p instance, as well as specifying they are unique from the IPFS ecosystem.
Includes a test to ensure peers with separate protocols do not find each other. I have also run external integration tests with a libp2p instance with no problems. I am open to adding more tests if there are more cases to test for.
The protocol to use can be specified by passing the `protocol` argument in the constructor argument, which defaults to what currently is in use: `"/ipfs/kad/1.0.0"`
The `multicodec` module export used in other js-libp2p packages still exports the same default value, so all external references to it should remain unaffected.
Please note, this may not …

Feature: adds custom multicodec protocol option

---

src/index.js
test/kad-dht.spec.js

Adds the ability for a dht key/value pair entry to be removed from the local datastore. This essentially acts as dereferencing functionality for the peer.
```js
await dht.removeLocal(uint8ArrayFromString('/v/hello'))
```

[Feature] adds removeLocal function

---

src/content-routing/index.js

If no content providers can be found, just be an empty iterator
instead of throwing.
This is necessary because multiple findProv strategies are tried
higher up the stack, at which point we make the decision whether
to throw or not.
This makes the behaviour consistent with the delegated content
routing module.

fix: do not throw on empty provider list

---

package.json

Webpack requires the `./` otherwise you get:
```
ERROR in ./node_modules/libp2p-kad-dht/src/routing-table/index.js 6:27-66
Module not found: Error: Can't resolve './generated-prefix-list.json' in '/Users/alex/test/webpack/node_modules/libp2p-kad-dht/src/routing-table'
```

fix: browser override path

---

src/content-fetching/index.js
src/content-routing/index.js
src/index.js
src/peer-routing/index.js
src/providers.js
src/query/worker-queue.js
src/routing-table/index.js
src/rpc/handlers/add-provider.js
src/rpc/handlers/get-providers.js
src/rpc/index.js
src/utils.js
test/kad-dht.spec.js
test/kad-utils.spec.js
test/network.spec.js
test/query.spec.js
test/rpc/handlers/add-provider.spec.js
test/rpc/handlers/get-providers.spec.js
test/rpc/handlers/get-value.spec.js
test/rpc/handlers/put-value.spec.js

Recent typescript has changed the default error type from `any` to `unknown` so we have to explicitly change it back to `any`.

chore: change error type

---

src/constants.js
src/providers.js
test/generate-peers/generate-peers.spec.js

Otherwise you get double slashes in datastore keys.

fix: remove trailing slash from datastore prefixes

---

.gitignore
src/dual-kad-dht.js

Only use peers we've managed to dial in attempted/success counts
for dht put operations

fix: count successful puts

---

src/dual-kad-dht.js
test/kad-dht.spec.js
test/rpc/handlers/get-value.spec.js

If no minPeers is specified, require at least one success during a
dht put operation, unless minPeers is explicitly `0`

fix: require at least one successful put

---

src/kad-dht.js
src/providers.js
src/routing-table/index.js
src/rpc/handlers/get-providers.js
src/topology-listener.js
test/utils/test-dht.js

If a remote peer doesn't have private addresses, do not add it to the
routing table for the lan DHT, if they don't have public addresses,
do not add them to the routing table for the wan DHT.
Also adds more logging.

fix: do not pollute routing table with useless peers

---

src/routing-table/index.js
src/routing-table/refresh.js
test/kad-dht.spec.js
test/routing-table.spec.js

We queue up ping requests to see if we should evict peers from the
routing table - if we are being shut down the requests will be
aborted so check to make sure we are still running before starting
another.
Also, don't evict a peer because the request failed if we aren't
running as it may have been cancelled which doesn't mean the remote
peer is invalid.

chore: guard on table refresh running

---

src/network.js

Otherwise we can end up dialing a node during libp2p shut down

fix: do not send messages if the network is not running

---

.github/workflows/test.yml

Not quite sure how the PRs that pulled the new peer-id/crypto passed but here we are.

chore: update node in ci

---

src/dual-kad-dht.js
src/kad-dht.js
test/kad-dht.spec.js

If we are in server mode, provide to the wan and the lan. If we are in client mode, only provide to the lan.

fix: only provide to wan in server mode

---

src/constants.js
src/kad-dht.js
src/query-self.js
src/query/manager.js
src/routing-table/refresh.js

If an `AbortSignal` is not passed to the query manager, create a
default timeout to prevent queries from running forever.
Also add configurable default timeouts for self-query and table refresh.

fix: add default query timeouts

---

src/query-self.js
test/kad-dht.spec.js

Increase the number of listeners allowed for the signal in the query-self query.

fix: silence max listeners exceeded warning

---

src/kad-dht.js

Instead of waiting for the query to end, just return the public key when we find it.

fix: return pk when found

---

README.md
package.json
src/content-routing/index.js
src/dual-kad-dht.js
src/kad-dht.js
src/peer-routing/index.js
src/rpc/handlers/add-provider.js
src/rpc/handlers/get-providers.js
src/rpc/handlers/get-value.js
src/rpc/handlers/index.js
src/rpc/index.js
src/topology-listener.js
src/types.ts
test/kad-dht.spec.js
test/rpc/handlers/add-provider.spec.js
test/rpc/handlers/get-value.spec.js
test/utils/test-dht.js

Refactors interfaces and classes used by `libp2p-interfaces` to use the async peer store from https://github.com/libp2p/js-libp2p/pull/1058
BREAKING CHANGE: peerstore methods are now all async

feat: async peer store

---

src/query-self.js
src/query/manager.js

fix: catch errors from setMaxListeners

---

package.json
src/query/manager.js
test/query.spec.js

`AbortController` and `AbortSignal` are in browsers and LTS node so the `abort-controller` and `native-abort-controller` deps aren't required any more.

fix: remove abort controller deps

---

src/dual-kad-dht.js
src/peer-routing/index.js
src/rpc/handlers/get-value.js

Datastore errors are thrown by some peerstore methods

fix: catch not found errors

---

src/query/manager.js
src/routing-table/index.js
src/types.ts

Latest libp2p switches to `{ system, component, metric, name }` as input

fix: update component metric API use

---

src/kad-dht.ts

So we can store and validate public key records out of the box.

fix: add record validators and selectors

---

src/query/manager.ts

The query timeout controller signal gets passed to all of the network operations etc that run during a query so can end up with lots of listeners for it's 'abort' event, which can trigger `MaxListenersExceededWarning` in node which warns of a memory leak, even though there is no leak.

fix: max listeners warning

---

src/rpc/handlers/find-node.ts
src/rpc/index.ts
test/rpc/handlers/find-node.spec.ts

Restores pre-1.x behaviour where when an RPC findNode request comes
in, if it's asking for us, return our info instead of looking for
closer peers which queries the routing table which may not have our
peer id in it.

fix: return self when asked for self

---

package.json
src/peer-list/peer-distance-list.ts

this module depends on node API making @libp2p/kad-dht unusable in browser.

fix: remove p-map dependency

---

package.json
src/index.ts
src/kad-dht.ts
src/network.ts
src/routing-table/index.ts
src/rpc/index.ts

After running an js-ipfs node for a week I noticed the lan routing table ping queue had 200k items in it (😱).  I think this is because we encounter lots of peers that are advertising their private addresses, they get added to the routing table, then we need to ping existing peers to see if we should evict them, which times out because the private addresses aren't routable.  We do this with `concurrency: 1` so it takes 10s to process each item in the queue but we are adding them to the queue at a much faster rate than that so it grows out of control.
Increasing the concurrency alleviates the queue pressure, so here we increase the default concurrency to 10 and expose it as a config option, as well as the timeout value to allow tuning by the user for their specific application.
We also add …

fix: increase ping concurrency

---

README.md

Solves issue #324 
**Issues addressed:**
1. Dead Peer Routing, Content Routing, Peer discovery badge images. 
2. Dead/incorrect `Open an issue...` link. This now points to the js-libp2p-kad-dht issues page, instead of a dead IPFS issues page. I also felt that pointing to the local issues page rather than IPFS was more reasonable (this is what other libp2p repos tend to do). 
3. Updated contributing badge to point to new URL. 
For the peer routing, etc. badges, I've linked the images to their respective deprecated and read-only repositories - this should prevent any future 404s and is what the updated libp2p-interfaces repo does. Clicking on the images will still redirect to the updated repositories. 
Please note that there's still a dead URL in the `dependency status` badge (below the …

docs: fix readme.md

---

src/content-routing/index.ts
test/kad-dht.spec.ts
test/utils/create-values.ts

This fixes a bug where `ADD_PROVIDER` message keys were CID bytes instead of multihash bytes, and changes the CIDs generated in tests to be V1s with `raw` codec instead of V0s so that the difference is actually tested..

fix: use multihash bytes for provide messages keys

---

src/index.ts
src/kad-dht.ts
test/kad-dht.spec.ts

The `Providers` component takes a `ProvidersInit` object, but there's not actually a way to provide it with one from the `KadDHT` constructor. This means users aren't able to override the defaults for how long provider records are valid for and how frequently to clean up expired provider records.
Feel free to close this if there's a different way you'd rather do it, or if for some reason it's not allowed on purpose (though I can't imagine why), but it's such a small change I thought I'd just open it as a PR.
Thanks for your time; this would really help me out!

feat: allow passing ProvidersInit in KadDHT constructor

---

src/providers.ts
test/network.spec.ts
test/providers.spec.ts
test/routing-table.spec.ts

p-queue@7.3.4 contained a breaking change so update it's use to get the correct return types.

fix: update p-queue types

---

src/routing-table/index.ts

As the `k-bucket` documentation [here](https://github.com/tristanls/k-bucket/blob/master/README.md#kbuckettoiterable) indicates, `toIterable` yields contact objects, **not** `KBucket` objects. Here, the contact objects are `KBucketPeer` objects.
You can check this in the code [here](https://github.com/tristanls/k-bucket/blob/3aa5b4f1dacb835752995a25409ab319d2070b9e/index.js#L413) - the delegated yield `yield * node.contacts` will yield each of the elements of the `node.contacts` array in order.

fix: correct `KBucketTree` types

---

package.json
src/query-self.ts
src/query/manager.ts
src/query/query-path.ts
src/routing-table/index.ts
src/routing-table/refresh.ts

Use `AbortSignal.timeout` instead of the `timeout-abort-controller` dep.
Refs: https://github.com/libp2p/js-libp2p/issues/1681

fix: remove timeout-abort-controller dependency

---

.gitignore
package.json
src/network.ts
test/network.spec.ts
test/rpc/index.node.ts

Updates stream types and abortable iterator

deps: update it-stream-types

---

src/routing-table/index.ts

Otherwise the log displays `[object Object]`

fix: log peer id not whole object

---

src/content-fetching/index.ts
src/content-routing/index.ts
src/kad-dht.ts
src/peer-routing/index.ts
src/query/manager.ts
test/query.spec.ts

Previously we chose peers before the self-query ran which meant there was a reasonable chance we chose 0 peers.
Instead, wait for the query to run, then choose peers to query.

fix: only choose query peers after initial self-query has run

---

package.json
src/content-fetching/index.ts
src/content-routing/index.ts
src/dual-kad-dht.ts
src/index.ts
src/network.ts
src/peer-routing/index.ts
src/query/events.ts
src/query/manager.ts
src/query/query-path.ts
test/kad-dht.spec.ts

Send DHT query events to the onProgress callback if one is passed to allow operation-specific progress events to pass up the stack.
Refs: https://github.com/libp2p/js-libp2p/issues/1574

feat: invoke onProgress callback if passed as an option

---

package.json
src/routing-table/index.ts
src/routing-table/k-bucket.ts
test/routing-table.spec.ts

Removes the k-bucket dep and imports the code here since the random bytes dep it uses doesn't work in browsers.
This PR can be reverted if https://github.com/tristanls/k-bucket/pull/53 is ever merged.

fix: work in browsers without extra deps
